---

weapons:
  - id: bow
    rangeMin: 1
    rangeMax: 3
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
      air: 1
    tagDamage:
      archer: 0.65
      soldier: 0.7
      villager: 0.7
      dog: 0.75
      spearman: 0.65
      balloon: 0.2
      wagon: 0.35                  
      mage: 0.75
      harpy: 0.3
      knight: 0.4
      witch: 0.2
      ballista: 0.3      
      trebuchet: 0.25
      giant: 0.1
      dragon: 0.1
      structure: 0.2
      commander: 0.05
      warship: 0.2
      harpoonship: 0.2
      turtle: 0.2
      travelboat: 0.2
      merman: 0.7
      rifleman: 0.8
      thief: 0.7

...
