---

weapons:
  - id: fireBreath
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.4
      soldier: 1.2
      villager: 1.2
      spearman: 1.2
      dog: 1.5
      wagon: 0.8
      knight: 1
      trebuchet: 1.05
      ballista: 1.1
      mage: 0.65
      structure: 0.65
      commander: 0.3 #from 0.35
      giant: 0.65
      rifleman: 1.3
      thief: 1.2
      
      warship: 0.9
      harpoonship: 0.7
      turtle: 0.75
      travelboat: 1.1
      merman: 1.2

...
