---

weapons:
  - id: giantSlam
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.5
      soldier: 1.3
      villager: 1.3
      spearman: 1
      dog: 1.5
      wagon: 0.75
      knight: 0.85
      trebuchet: 1.05
      ballista: 1
      merman: 1.3
      mage: 1.1
      structure: 0.85
      giant: 0.45
      commander: 0.25 #from 0.35
      rifleman: 1.4
      thief: 1.3

...
