---

unitClasses:
  - id: harpy
    name: unit_class_name_harpy
    cost: 600
    movement: hovering
    moveRange: 5
    damageMultiplier: 1.0
    aiPriority: 1.0
    weapons:
      - id: harpyClaws
    tags:
      - harpy
      - type.air
    battleUnitCount: 4
    passiveMultiplier: 1.5
    sightRange: 5
    canSeeOverTerrain: true

weapons:
  - id: harpyClaws
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
      air: 1
      water: 1
    tagDamage:
      archer: 0.75
      soldier: 0.65
      villager: 0.65
      spearman: 0.50 # from 0.45
      dog: 0.55
      wagon: 0.35
      knight: 0.75
      balloon: 0.55
      trebuchet: 0.55
      ballista: 0.35
      witch: 0.30
      dragon: 0.35
      mage: 0.25
      harpy: 0.55
      structure: 0.5
      giant: 0.10
      commander: 0.10 #from .15
      rifleman: 0.75
      thief: 0.65

      warship: 0.45
      harpoonship: 0.25
      turtle: 0.25
      travelboat: 0.35
      merman: 0.65

...
