---

weapons:
  - id: lance
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1
      soldier: 0.9
      villager: 0.9
      spearman: 0.45
      dog: 1.2
      wagon: 0.55
      knight: 0.55
      trebuchet: 0.8
      ballista: 0.85
      merman: 0.85
      mage: 1.1
      structure: 0.65
      giant: 0.25
      commander: 0.2 #from 0.25
      rifleman: 1.0
      thief: 0.9
...
