---

unitClasses:
  - id: mana_indicator
    name: structure_name_mana_indicator
    movement: walking
    aiPriority: 0.0
    cargoSpace: 1
    moveRange: 1
    battleUnitCount: 1
    damageMultiplier: 1
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: false
    income: 0
    cost: 500
    regeneration: 10
    tags: []
    verbs:
      - load
    sightRange: 1
    grooveId: indicate_mana
    isSpawnable: false
    isHidden: true
    palettePriority: 1
    isRecruitable: false


units:
  - class: mana_indicator
    faction: neutral
    name: structure_name_mana_indicator
    mapAnimation: units/mana_indicator/map_mana_indicator_cherrystone
    battleAnimation: units/commanders/emeric/battle_crystal
    smallPortrait: units/commanders/emeric/portrait_crystal_small.png
    mediumPortrait: units/commanders/emeric/portrait_crystal_medium.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    runsIn: false
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      death: emeric/emericCrystalDie
      deathMap: unitDie
      deathMapNoBattle: emeric/emericCrystalDie
      hit: hitStone
      hitMap: hitStone

...
