---

# This is the string configuration file for English.
en-GB:
  # New Archer
  unit_class_name_new_archer: "New Archer"
  unit_description_new_archer: "Ranged ground units able to move and attack in the same turn. Critical hit when stationary. Same as old archer basically."
  unit_name_new_archer_cherrystone: "New Ranger"
  unit_name_new_archer_felheim: "New Dreadbow"
  unit_name_new_archer_heavensong: "New Hawkbow"
  unit_name_new_archer_floran: "New Shooter"

  # Mana Crystal
  structure_name_mana_crystal: "Mana Crystal"
  unit_description_mana_crystal: "A crystal which increases the owner's mana by 1"

  # Unused Mana Indicator
  structure_name_mana_indicator: "Mana Crystal"
  unit_description_mana_indicatorl: "A crystal which increases the owner's mana by 1"
  groove_name_indicate_mana: "None"
  groove_description_indicate_mana: "None"

  # Triggers
  trigger_action_name_set_state: "Set State"                                                                            # The name
  trigger_action_description_set_state: "Sets the unit state."                                                          # The general description
  trigger_action_readable_set_state: Add set state {3} to {4} for unit type(s) {0} at location {1} owned by player {2}. # Numbers are filled in by user choices.

  trigger_condition_name_state: "Has State"                                                                                   # The name
  trigger_condition_description_state: "Triggers if a unit has a particular state."                                           # The general description
  trigger_condition_readable_state: "If unit type(s) {0} at location {1} owned by player {2} have state {3} equal to {4}."    # Numbers are filled in by user choices.

  # Verbs
  ui_unit_verbs_swim_under: Swim Under
  ui_unit_verbs_free_turn: Free Move

  groove_name_diplomacy: Diplomacy
  
  # CODEX
  # Overhealing
  codex_projectgroove_overheal: "Overheal"
  codex_rules_projectgroove_overheal_title: "Overhealing\n(Project Groove mod)"
  codex_rules_projectgroove_overheal_text_1: "Overhealing is a system of giving units above 100% health through some abilities. Overhealed units have the following attributes:\n> Healing will not restore their health above 100%.\n> Damage dealt increases proportional to their health."
  codex_rules_projectgroove_overheal_text_2: "> Defence is restricted to the effects of 100% health.\n> Commanders will immediately return to 100% health on the start of their next turn.\n> Overhealed units will display a flashing Heart icon."
  
  # Mana
  codex_projectgroove_mana: "Mana"
  codex_rules_projectgroove_mana_title: "Mana\n(Project Groove mod)"
  codex_rules_projectgroove_mana_text_1: "Mana is a unique resource, generated by Mana Crystals, a special building type. It is used for Spells and Recruiting certain units. This includes the following:\n> Spells: Heal, Hex\n> Units: Mage, Giant, Sky Rider, Dragon."
  codex_rules_projectgroove_mana_text_2: "Remaining Mana is displayed as Groove on ally Strongholds. Mana has the following attributes:\n> Mana Crystals provide 1 Mana at the start of each turn.\n> All remaining Mana will be lost at the end of the turn, and cannot be spent"
...
