---

terrains:
  - id: bridge
    name: terrain_name_bridge
    defenceBonus: 0
    movementCost:
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      wheels: 1
      amphibious: 2
      sailing: 3  # from 2
    cantStop: [sailing]
    movementGroupType: land
    placeable: true
    tilesets: 
      0: plains
      1: [sea, river]
      2: bridge

  - id: sea
    name: terrain_name_sea
    biomeNames:
      volcano: terrain_name_sea_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    defenceBonus: 1
    movementCost:
      sailing: 3  # from 2
      flying: 1
      hovering: 1
      amphibious: 1
      sea_building: 1
    movementGroupType: water
    placeable: true
    tilesets:
      0: plains
      1: sea

  - id: ocean
    name: terrain_name_ocean
    biomeNames:
      volcano: terrain_name_ocean_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    defenceBonus: 0
    movementCost:
      sailing: 2  # from 1
      flying: 1
      hovering: 1
      amphibious: 1
      sea_building: 1
    movementGroupType: water
    placeable: true
    tilesets:
      1: ocean

  - id: reef
    name: terrain_name_reef
    biomeNames:
      volcano: terrain_name_reef_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    defenceBonus: 3  # from 2
    movementCost:
      sailing: 6  # from 4
      flying: 1
      hovering: 1
      amphibious: 2
      sea_building: 1
    movementGroupType: water
    placeable: true
    fowCover: true
    tilesets: 
      0: plains
      1: sea
      2: reef

  - id: beach
    name: terrain_name_beach
    defenceBonus: -1
    movementCost:
      sailing: 3  # from 2
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      amphibious: 2
    movementGroupType: land
    placeable: true
    tilesets:
      0: plains
      1: beach

...